"""Public package boundary for the Lilavel persistent-agent kernel."""

from lilavel_contracts import ToolCall, ToolEffect, ToolResult, ToolResultStatus, ToolSpec

from .contracts import (
    ActionExecutor,
    DirectMessageWakePolicy,
    EnvironmentAdapter,
    EventRouter,
    EventSource,
    EventSubmitter,
    EventTrust,
    JsonValue,
    NeverWakePolicy,
    WakeDecision,
    WakePolicy,
    WorldEvent,
)
from .conversation_router import (
    PRESENTATION_ABORT,
    PRESENTATION_BIND,
    PRESENTATION_COMPLETE,
    PRESENTATION_DELTA,
    PRESENTATION_FAILED,
    PRESENTATION_INTERRUPTED,
    PRESENTATION_OPEN,
    PRESENTATION_WATCH,
    CoreConversationRouter,
)
from .kernel import (
    DuplicateEnvironment,
    DuplicateTool,
    LilavelRuntime,
    LilavelRuntimeError,
    LilavelRuntimeHealth,
    RuntimeFailed,
    RuntimeNotRunning,
    RuntimeRegistrationClosed,
    RuntimeShutdownTimeout,
    RuntimeState,
)
from .tool_session import (
    DeterministicToolSession,
    DeterministicToolSessionFactory,
    FakeToolDecision,
    FakeToolExecutor,
    ToolSessionEvidence,
)

__version__ = "0.1.0"

__all__ = [
    "ActionExecutor",
    "CoreConversationRouter",
    "DirectMessageWakePolicy",
    "DeterministicToolSession",
    "DeterministicToolSessionFactory",
    "DuplicateEnvironment",
    "DuplicateTool",
    "EnvironmentAdapter",
    "EventRouter",
    "EventSource",
    "EventSubmitter",
    "EventTrust",
    "FakeToolDecision",
    "FakeToolExecutor",
    "JsonValue",
    "LilavelRuntime",
    "LilavelRuntimeError",
    "LilavelRuntimeHealth",
    "NeverWakePolicy",
    "PRESENTATION_ABORT",
    "PRESENTATION_BIND",
    "PRESENTATION_COMPLETE",
    "PRESENTATION_DELTA",
    "PRESENTATION_FAILED",
    "PRESENTATION_INTERRUPTED",
    "PRESENTATION_OPEN",
    "PRESENTATION_WATCH",
    "RuntimeFailed",
    "RuntimeNotRunning",
    "RuntimeRegistrationClosed",
    "RuntimeShutdownTimeout",
    "RuntimeState",
    "ToolCall",
    "ToolEffect",
    "ToolResult",
    "ToolResultStatus",
    "ToolSpec",
    "ToolSessionEvidence",
    "WakeDecision",
    "WakePolicy",
    "WorldEvent",
    "__version__",
]
