"""Public package boundary for the Lilavel persistent-agent kernel."""

from lilavel_contracts import ToolCall, ToolEffect, ToolResult, ToolResultStatus, ToolSpec

from .contracts import (
    ActionExecutor,
    DirectMessageWakePolicy,
    EnvironmentAdapter,
    EventRouter,
    EventSource,
    EventSubmitter,
    EventTrust,
    JsonValue,
    NeverWakePolicy,
    WakeDecision,
    WakePolicy,
    WorldEvent,
)
from .conversation_router import (
    PRESENTATION_ABORT,
    PRESENTATION_BIND,
    PRESENTATION_COMPLETE,
    PRESENTATION_DELTA,
    PRESENTATION_FAILED,
    PRESENTATION_INTERRUPTED,
    PRESENTATION_OPEN,
    PRESENTATION_WATCH,
    CoreConversationRouter,
)
from .kernel import (
    DuplicateEnvironment,
    DuplicateTool,
    LilavelRuntime,
    LilavelRuntimeError,
    LilavelRuntimeHealth,
    RuntimeFailed,
    RuntimeNotRunning,
    RuntimeRegistrationClosed,
    RuntimeShutdownTimeout,
    RuntimeState,
)
from .tool_registry import (
    MAX_EXPOSED_TOOL_BYTES,
    MAX_EXPOSED_TOOLS,
    ApplicationToolRegistry,
    DuplicateToolBinding,
    ToolAuthorization,
    ToolAuthorizationHook,
    ToolAvailabilityHook,
    ToolBinding,
    ToolExecutor,
    ToolExposureError,
    ToolExposureSnapshot,
    ToolRegistrationError,
    UnsupportedToolSchema,
    validate_tool_arguments,
)
from .tool_session import (
    DeterministicToolSession,
    DeterministicToolSessionFactory,
    FakeToolDecision,
    FakeToolExecutor,
    ToolSessionEvidence,
)

__version__ = "0.1.0"

__all__ = [
    "ActionExecutor",
    "ApplicationToolRegistry",
    "CoreConversationRouter",
    "DirectMessageWakePolicy",
    "DeterministicToolSession",
    "DeterministicToolSessionFactory",
    "DuplicateToolBinding",
    "DuplicateEnvironment",
    "DuplicateTool",
    "EnvironmentAdapter",
    "EventRouter",
    "EventSource",
    "EventSubmitter",
    "EventTrust",
    "FakeToolDecision",
    "FakeToolExecutor",
    "JsonValue",
    "LilavelRuntime",
    "LilavelRuntimeError",
    "LilavelRuntimeHealth",
    "MAX_EXPOSED_TOOL_BYTES",
    "MAX_EXPOSED_TOOLS",
    "NeverWakePolicy",
    "PRESENTATION_ABORT",
    "PRESENTATION_BIND",
    "PRESENTATION_COMPLETE",
    "PRESENTATION_DELTA",
    "PRESENTATION_FAILED",
    "PRESENTATION_INTERRUPTED",
    "PRESENTATION_OPEN",
    "PRESENTATION_WATCH",
    "RuntimeFailed",
    "RuntimeNotRunning",
    "RuntimeRegistrationClosed",
    "RuntimeShutdownTimeout",
    "RuntimeState",
    "ToolCall",
    "ToolAuthorization",
    "ToolAuthorizationHook",
    "ToolAvailabilityHook",
    "ToolBinding",
    "ToolEffect",
    "ToolResult",
    "ToolResultStatus",
    "ToolSpec",
    "ToolSessionEvidence",
    "ToolExposureError",
    "ToolExposureSnapshot",
    "ToolExecutor",
    "ToolRegistrationError",
    "UnsupportedToolSchema",
    "WakeDecision",
    "WakePolicy",
    "WorldEvent",
    "validate_tool_arguments",
    "__version__",
]
